// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: usermsg/usermsg.proto

package go_usermsg_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ID   int32  `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Jugada_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`                             //ID jugador
	NElegido int32 `protobuf:"varint,2,opt,name=n_elegido,json=nElegido,proto3" json:"n_elegido,omitempty"` //número elegido por el jugador
}

func (x *Jugada_1) Reset() {
	*x = Jugada_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugada_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugada_1) ProtoMessage() {}

func (x *Jugada_1) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugada_1.ProtoReflect.Descriptor instead.
func (*Jugada_1) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{2}
}

func (x *Jugada_1) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Jugada_1) GetNElegido() int32 {
	if x != nil {
		return x.NElegido
	}
	return 0
}

type Resp_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Binario  int32  `protobuf:"varint,1,opt,name=binario,proto3" json:"binario,omitempty"`                  // 0 si el jugador eligió un número igual o mayor al Lider
	Ronda    int32  `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`                      //la ronda la cual se está jugando
	EstJuego string `protobuf:"bytes,3,opt,name=est_juego,json=estJuego,proto3" json:"est_juego,omitempty"` //estado del juego (en caso de que sea el único en sobrevivir y ganar)
}

func (x *Resp_1) Reset() {
	*x = Resp_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp_1) ProtoMessage() {}

func (x *Resp_1) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp_1.ProtoReflect.Descriptor instead.
func (*Resp_1) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{3}
}

func (x *Resp_1) GetBinario() int32 {
	if x != nil {
		return x.Binario
	}
	return 0
}

func (x *Resp_1) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

func (x *Resp_1) GetEstJuego() string {
	if x != nil {
		return x.EstJuego
	}
	return ""
}

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req string `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{4}
}

func (x *Req) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

type Monto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto int32 `protobuf:"varint,1,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *Monto) Reset() {
	*x = Monto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Monto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monto) ProtoMessage() {}

func (x *Monto) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monto.ProtoReflect.Descriptor instead.
func (*Monto) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{5}
}

func (x *Monto) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

type Jugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Juego  string `protobuf:"bytes,2,opt,name=juego,proto3" json:"juego,omitempty"`
	Ronda  string `protobuf:"bytes,3,opt,name=ronda,proto3" json:"ronda,omitempty"`
	Jugada int32  `protobuf:"varint,4,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *Jugada) Reset() {
	*x = Jugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugada) ProtoMessage() {}

func (x *Jugada) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugada.ProtoReflect.Descriptor instead.
func (*Jugada) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{6}
}

func (x *Jugada) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Jugada) GetJuego() string {
	if x != nil {
		return x.Juego
	}
	return ""
}

func (x *Jugada) GetRonda() string {
	if x != nil {
		return x.Ronda
	}
	return ""
}

func (x *Jugada) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

type Registro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *Registro) Reset() {
	*x = Registro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Registro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registro) ProtoMessage() {}

func (x *Registro) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registro.ProtoReflect.Descriptor instead.
func (*Registro) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{7}
}

func (x *Registro) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type Check struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Check string `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
}

func (x *Check) Reset() {
	*x = Check{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermsg_usermsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_usermsg_usermsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_usermsg_usermsg_proto_rawDescGZIP(), []int{8}
}

func (x *Check) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

var File_usermsg_usermsg_proto protoreflect.FileDescriptor

var file_usermsg_usermsg_proto_rawDesc = []byte{
	0x0a, 0x15, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73, 0x67,
	0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x2a, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x22, 0x37, 0x0a, 0x08, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x5f, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x5f, 0x65, 0x6c, 0x65,
	0x67, 0x69, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x45, 0x6c, 0x65,
	0x67, 0x69, 0x64, 0x6f, 0x22, 0x55, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x70, 0x5f, 0x31, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e, 0x64,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x73, 0x74, 0x5f, 0x6a, 0x75, 0x65, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x73, 0x74, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x22, 0x17, 0x0a, 0x03, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x72, 0x65, 0x71, 0x22, 0x1d, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f,
	0x6e, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x6a, 0x75, 0x65, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x75,
	0x65, 0x67, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64,
	0x61, 0x22, 0x26, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x32, 0x9f, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x64,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x4e, 0x65,
	0x77, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73,
	0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x6d, 0x73, 0x67, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0e, 0x4c, 0x75,
	0x7a, 0x5f, 0x52, 0x6f, 0x6a, 0x61, 0x5f, 0x56, 0x65, 0x72, 0x64, 0x65, 0x12, 0x11, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x6d, 0x73, 0x67, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x5f, 0x31, 0x1a,
	0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x5f, 0x31,
	0x22, 0x00, 0x12, 0x26, 0x0a, 0x04, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x0c, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d,
	0x73, 0x67, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x22, 0x00, 0x32, 0x3b, 0x0a, 0x0c, 0x50, 0x6f,
	0x7a, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x4d, 0x6f,
	0x6e, 0x74, 0x6f, 0x50, 0x6f, 0x7a, 0x6f, 0x12, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73,
	0x67, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73, 0x67, 0x2e,
	0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x22, 0x00, 0x32, 0x40, 0x0a, 0x08, 0x4e, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73, 0x67, 0x2e, 0x4a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x1a, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73, 0x67, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x22, 0x00, 0x32, 0x3e, 0x0a, 0x08, 0x44, 0x61, 0x74,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73, 0x67,
	0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x1a, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x73,
	0x67, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x75, 0x73, 0x65,
	0x72, 0x6d, 0x73, 0x67, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x6f, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x6d, 0x73, 0x67, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_usermsg_usermsg_proto_rawDescOnce sync.Once
	file_usermsg_usermsg_proto_rawDescData = file_usermsg_usermsg_proto_rawDesc
)

func file_usermsg_usermsg_proto_rawDescGZIP() []byte {
	file_usermsg_usermsg_proto_rawDescOnce.Do(func() {
		file_usermsg_usermsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_usermsg_usermsg_proto_rawDescData)
	})
	return file_usermsg_usermsg_proto_rawDescData
}

var file_usermsg_usermsg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_usermsg_usermsg_proto_goTypes = []interface{}{
	(*Message)(nil),  // 0: usermsg.Message
	(*User)(nil),     // 1: usermsg.User
	(*Jugada_1)(nil), // 2: usermsg.Jugada_1
	(*Resp_1)(nil),   // 3: usermsg.Resp_1
	(*Req)(nil),      // 4: usermsg.Req
	(*Monto)(nil),    // 5: usermsg.Monto
	(*Jugada)(nil),   // 6: usermsg.Jugada
	(*Registro)(nil), // 7: usermsg.Registro
	(*Check)(nil),    // 8: usermsg.Check
}
var file_usermsg_usermsg_proto_depIdxs = []int32{
	0, // 0: usermsg.LiderServices.NewPlayer:input_type -> usermsg.Message
	2, // 1: usermsg.LiderServices.Luz_Roja_Verde:input_type -> usermsg.Jugada_1
	4, // 2: usermsg.LiderServices.Pozo:input_type -> usermsg.Req
	4, // 3: usermsg.PozoServices.MontoPozo:input_type -> usermsg.Req
	6, // 4: usermsg.NameNode.JugadaPlayer:input_type -> usermsg.Jugada
	6, // 5: usermsg.DataNode.RegistrarInfo:input_type -> usermsg.Jugada
	1, // 6: usermsg.LiderServices.NewPlayer:output_type -> usermsg.User
	3, // 7: usermsg.LiderServices.Luz_Roja_Verde:output_type -> usermsg.Resp_1
	5, // 8: usermsg.LiderServices.Pozo:output_type -> usermsg.Monto
	5, // 9: usermsg.PozoServices.MontoPozo:output_type -> usermsg.Monto
	7, // 10: usermsg.NameNode.JugadaPlayer:output_type -> usermsg.Registro
	8, // 11: usermsg.DataNode.RegistrarInfo:output_type -> usermsg.Check
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_usermsg_usermsg_proto_init() }
func file_usermsg_usermsg_proto_init() {
	if File_usermsg_usermsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_usermsg_usermsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermsg_usermsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermsg_usermsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugada_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermsg_usermsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermsg_usermsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermsg_usermsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Monto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermsg_usermsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermsg_usermsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Registro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermsg_usermsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Check); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usermsg_usermsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_usermsg_usermsg_proto_goTypes,
		DependencyIndexes: file_usermsg_usermsg_proto_depIdxs,
		MessageInfos:      file_usermsg_usermsg_proto_msgTypes,
	}.Build()
	File_usermsg_usermsg_proto = out.File
	file_usermsg_usermsg_proto_rawDesc = nil
	file_usermsg_usermsg_proto_goTypes = nil
	file_usermsg_usermsg_proto_depIdxs = nil
}
